version: "3.8"

services:
  shopwise:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopwise
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
