services:
  - type: web
    name: shopwise
    runtime: docker
    rootDir: .
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 5000
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL_NAME
        sync: false
      - key: GEMINI_PROJECT_ID
        sync: false
