-- Add subscription info columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS plan VARCHAR(255) DEFAULT 'BASIC' NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS finished_free_trial BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS free_trial_started_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscribed_at TIMESTAMP;
